image: 683422241496.dkr.ecr.us-east-1.amazonaws.com/cd-rails-base:latest

stages:
  - test

cucumber:
  tags:
    - ruby
  stage: test
  services:
    - mysql:5.7
  script:
    - rename 's/.sample//' config/*.sample
    - bundle install --jobs $(nproc) --path=/cache/bundler
    - rake bower:install[--allow-root] bower:resolve
    - mysqladmin -uroot -h mysql create ppush-console_test
    - RAILS_ENV=test bundle exec rake db:migrate db:seed
    - mkdir test-plans
    - xvfb-run -a --server-args="-screen 0 1680x1000x24" bundle exec cucumber -f EcoworkFormatter -o test-plans/ppush-console.html
    - yard config load_plugins true
    - yardoc 'app/**/*.rb' 'features/**/*.feature'
  artifacts:
    paths:
      - test-plans/
      - doc
  only:
    - develop
